### PR TITLE
upgrade graceful-fs to 4.1.3

### PR DESCRIPTION
**Pull request by thefourtheye**
fixes: https://github.com/bower/decompress-zip/issues/52

### CODE REVIEW

**Comment by develar** [comment]
+1 Please accept pull request.

**Comment by ngoldman** [comment]
```
npm WARN  graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

This is an underlying dependency for [electron-packager](https://github.com/electron-userland/electron-packager), hoping to fix this issue up the chain from here.

```
electron-packager@5.2.1
├ asar@0.8.3
└─┬ mksnapshot@0.1.0
  └─┬ decompress-zip@0.1.0
    └─ graceful-fs@3.0.8
```

**Comment by zeke** [comment]
> This is an underlying dependency for electron-packager, hoping to fix this issue up the chain from here.

Same here. cc @wibblymat and @sindresorhus

**Comment by BenMann** [comment]
cc @sheerun
Should be fine, right?

**Comment by sheerun** [comment]
@thefourtheye @zeke @ungoldman @develar What are the braking changes for graceful-fs 4.x?

**Comment by thefourtheye** [comment]
@shreerun As far as I know there is nothing. Before v4 [this](https://github.com/nodejs/node/issues/1898#issuecomment-109259158) was the actual problem faced by graceful-fs. In 4.0 it was fixed in a backward compatible manner.

**Comment by sheerun** [comment]
Well, I don't want to guess.. You want half of the community to do major upgrade of graceful-fs, but there isn't even a changelog available: https://github.com/isaacs/node-graceful-fs/issues/51

**Comment by zeke** [comment]
Maybe @isaacs can shed some :bulb: on the matter...

**Comment by sheerun** [comment]
released as 0.2.1

**Comment by zeke** [comment]
Thank you, @sheerun!

**Pull request merged**
