### PR TITLE
Added file mode preservation

### PR DESCRIPTION
**Pull request by szwacz**
Fixes https://github.com/bower/decompress-zip/issues/22

### CODE REVIEW

**Comment by sindresorhus** [comment]
Merge conflicts needs to be resolved ;)

**Comment by szwacz** [comment]
Yey! Ok, I'll fix this and add some tests tomorrow or on Tuesday. Please stay tuned ;)

**Comment by sheerun** [comment]
@szwacz I've merged your PR with tests refactor to master and even added coveralls support :)

**Comment by szwacz** [comment]
All right. Here are unit tests.

**Comment by szwacz** [comment]
One more thing...
My code doesn't cover case when you extract stuff into nonexistent folder, e.g.
```js
zip.extract({ path: 'completely/new/path' });
```
Folders completely/new/path don't exist, so DecompressZip will create them, but there is no direct way to set their mode. Of course we can do something like:
```js
zip.extract({ path: 'completely/new/path', modeForNonexistentDirectories: '777' });
```
But I don't know if this feature will be used at all. What do you think?

**Comment by szwacz** [comment]
Ok, ignore what I've written one comment above. If someone wants to have folders with certain mode he or she could create them bofore unpacking or chmod them after unpacking. It doesn't make sense to add this to DecompressZip.

**Comment by szwacz** [comment]
Ping?

**Comment by iwege** [comment]
+1 for this PR

**Comment by brian-mann** [comment]
+1 could use this!

**Pull request merged**
